#+title: Emacs Config (Doom Emacs)
#+author: Tim Hawes
#+property: header-args :tangle yes :mkdirp yes
#+startup: overview

* Headings
** Packages File
Create the packages.el file.
#+BEGIN_SRC emacs-lisp :tangle packages.el
;; -*- no-byte-compile: t; -*-
;;; $DOOMDIR/packages.el
#+END_SRC
** Config file header
#+BEGIN_SRC emacs-lisp
;;; $DOOMDIR/config.el -*- lexical-binding: t; -*-

#+END_SRC
* Identification
Some functionality uses this to identify you, e.g. GPG configuration, email clients, file templates and snippets.
#+BEGIN_SRC emacs-lisp
(setq user-full-name "Tim Hawes"
      user-mail-address "trhawes@gmail.com"
      github-account-name "timotheosh")
#+END_SRC
* Emacs-lisp libraries
These are essential libraries that make programming in elisp much better (and consistent). I am trying to be picky, and hope the chosen libraries are something that are being considered for use in emacs-core in the future. One can dream, can't they?
** dash: A modern list API for Emacs.
Dash is included in Doom Emacs, so this is not tangled by default. All libraries Doom uses is pinned to specific versions.
#+begin_src emacs-lisp :tangle no
;; Dash is maintained regularly, so check the pinned version before enabling.
;; The specified pin might be too old.
(package! dash :recipe (:host github :repo "magnars/dash.el") :pin "aab346e") ;; Commit data 2021-6-2
#+end_src
** ht for better hash-map manipulation
[[https://www.emacswiki.org/emacs/HashMap][EmacsWiki references]] this library as a "more consistent and extensive interfave to hash-tables".

*** Why?
From the [[https://github.com/Wilfred/ht.el#why][project page]]:
Libraries like [[https://github.com/magnars/s.el][s.el]] (strings) and [[https://github.com/magnars/dash.el][dash.el]] (lists) have shown how much nicer Emacs lisp programming can be with good libraries. ht.el aims to similarly simplify working with hash tables.

Common operations with hash tables (e.g. enumerate the keys) are too difficult in Emacs lisp.

ht.el offers:
- A consistent naming scheme (contrast make-hash-table with puthash)
- A more natural argument ordering
- Mutation functions always return nil
- A more comprehensive range of hash table operations, including a conventional map (ht-map returns a list, elisp's maphash returns nil).
#+begin_src emacs-lisp :tangle packages.el
(package! ht :recipe (:host github :repo "Wilfred/ht.el") :pin "c4c1be4") ;; Commit date 2021-1-19
#+end_src
** s.el for string manipulations
I like this, but have not yet decided to use it. I have seen it used a lot in various melpa packages.
#+begin_src emacs-lisp :tangle no
(package! s :recipe (:host github :repo "magnars/s.el") :pin "e1710af") ;;Commit date 2021-6-3
#+end_src
** term-keys
To get the GUI key memory activbe in the terminal.
*** package
#+begin_src emacs-lisp :tangle packages.el
(package! term-keys :recipe (:host github :repo "CyberShadow/term-keys")
  :pin "25b6316") ;; Commit date Jun 13, 2022
#+end_src
*** config
#+begin_src emacs-lisp
(when (not window-system)
  (term-keys-mode t)
  (after! smartparens-mode
    (map! "<prior>" #'scroll-up-command)
    (map! "<next>" #'scroll-down-command)))
#+end_src

* Global
** COMMENT Personal functions
~system-type~ is too vague when it comes to BSD UNIX. We'll run uname -s to get the system name.
#+begin_src emacs-lisp
(if (executable-find "uname")
    (setq uname-system (intern (string-trim (shell-command-to-string "uname -s"))))
  (setq uname-system nil))

#+end_src
** Disable global smartparens-mode
Smartparens is awesome, but we don't want it everywhere.
#+BEGIN_SRC emacs-lisp
(remove-hook 'doom-first-buffer-hook #'smartparens-global-mode)
(setq! show-paren-mode 1
       doom-scratch-initial-major-mode t)
#+END_SRC
** Long lines
*** Bidirectional Editing
Disable bidirectional editing. NOTE: You'll need to change this if you decide to write someing in Hebrew or Chinese.
#+begin_src emacs-lisp
(setq-default bidi-paragraph-direction 'left-to-right)
#+end_src
*** Bidirectional parenthesis
Same applies from Bidirectional Editing above.
#+begin_src emacs-lisp
(if (version<= "27.1" emacs-version)
    (setq bidi-inhibit-bpa t))
#+end_src
*** So-long mode
Disable this and use ~find-file-literally~ instead, if you don't want this globally.
#+begin_src emacs-lisp
;;(if (version<= "27.1" emacs-version)
;;    (global-so-long-mode 1))
#+end_src
** auth-sources (authinfo)
#+begin_src emacs-lisp
(setq! auth-sources '("~/.authinfo.gpg")
       epg-gpg-program "gpg2")
#+end_src
* Appearance
*** Fixed Font
#+begin_src emacs-lisp
(if (and window-system (font-info (font-spec :family "Iosevka" :size 14.0)))
      (setq doom-font (font-spec :family "Iosevka" :size 14.0)))
;; In case we are runnning in daemon mode
(defun my/set-fixed-font (frame)
  (select-frame frame)
  (if (and window-system (font-info (font-spec :family "Iosevka" :size 14.0)))
      (setq doom-font (font-spec :family "Iosevka" :size 14.0))))
#+end_src
*** Variable Font
#+begin_src emacs-lisp
(if (and window-system (font-info (font-spec :family "ETBookOT" :size 18.0)))
      (setq doom-variable-pitch-font (font-spec :family "ETBookOT" :size 18.0)))
;; In case we are runnning in daemon mode
(defun my/set-variable-font (frame)
  (select-frame frame)
  (if (and window-system (font-info (font-spec :family "ETBookOT" :size 18.0)))
      (setq doom-variable-pitch-font (font-spec :family "ETBookOT" :size 18.0))))
#+end_src
*** Set fonts on frame creation
#+begin_src emacs-lisp
(push 'my/set-variable-font after-make-frame-functions)
(push 'my/set-fixed-font after-make-frame-functions)
#+end_src
** Mixed-pitch Fonts
*** Package
#+BEGIN_SRC emacs-lisp :tangle packages.el
(package! mixed-pitch)
#+END_SRC
*** Config
#+BEGIN_SRC emacs-lisp
(setq! mixed-pitched-variable-pitch-cursor 'bar)
#+END_SRC
** Olivetti Mode
*** Package
#+BEGIN_SRC emacs-lisp :tangle packages.el
(package! olivetti)
#+END_SRC
** Theme
There are two ways to load a theme. Both assume the theme is installed and available. You can either set ~doom-theme~ or manually load a theme with the ~load-theme~ function. This is the default:
#+BEGIN_SRC emacs-lisp
(setq doom-theme 'doom-one)
#+END_SRC
** Set Banner
#+BEGIN_SRC emacs-lisp
(setq fancy-splash-image
      (concat doom-private-dir "banners/" "emacs-pen-3d.png"))
#+END_SRC
** Line number style
This determines the style of line numbers in effect. If set to `nil', line numbers are disabled. For relative line numbers, set this to `relative'.
#+BEGIN_SRC emacs-lisp
(setq display-line-numbers-type t)
#+END_SRC
* Key Maps
** Global keys
~overwrite-mode~ in Emacs is a huge nuissasnce to me. It is a trap, not a feature. So disable its key.
#+begin_src emacs-lisp
(global-unset-key (kbd "<insert>"))
#+end_src
** Centaur Tabs
#+BEGIN_SRC emacs-lisp
(map! :map centaur-tabs-mode-map
      :g "C-<prior>" #'centaur-tabs-backward
      :g "C-<next>" #'centaur-tabs-forward)
#+END_SRC
** Return counsel-find-file back to its default behavior
#+BEGIN_SRC emacs-lisp
(after! ivy
  (map! :map ivy-minibuffer-map
        :g "TAB" #'ivy-partial)
  (setq! counsel-projectile-preview-buffers t
         counsel-switch-buffer-preview-virtual-buffers t)

  (map! "C-x b"
        #'counsel-projectile-switch-to-buffer)

  (map! "C-x B" #'counsel-switch-buffer)
  (map! :map counsel-M-x-map
        :g "TAB" #'ivy-partial))
#+END_SRC
** Projectile-find-file
F4 gives us ~counsel-projectile-find-file~
#+BEGIN_SRC emacs-lisp
(global-set-key (kbd "<F4>") 'counsel-projectile-find-file)
#+END_SRC
* Additional Modules
** Perspective.el
*** Package
#+begin_src emacs-lisp :tangle no
(package! perspective :recipe (:host github :repo "nex3/perspective-el")
  :pin "d8211a8") ;; Commit Date Dec 12, 2021
#+end_src
*** Config
#+begin_src emacs-lisp :tangle no
(use-package! perspective
  :bind (("C-x b" . persp-counsel-switch-buffer)
         ("C-x x s" . persp-switch))
  :config
  (persp-mode))
#+end_src
** Swiper
Better isearch replacement
#+BEGIN_SRC emacs-lisp :tangle packages.el
(package! swiper :recipe (:host github :repo "abo-abo/swiper") :pin "7c5d49f") ;; commit date: 2021/05/18
#+END_SRC
#+BEGIN_SRC emacs-lisp
(map! "C-s" #'swiper)
#+END_SRC
** [[https://github.com/lastquestion/explain-pause-mode][explain-pause-mode]]
explain-pause-mode is very lightweight; you can leave it running all the time. You can check the buffer ~*explain-pause-log*~ to see what was slow and the information gathered.
#+BEGIN_SRC emacs-lisp :tangle packages.el
(package! explain-pause-mode :recipe
  (:host github :repo "lastquestion/explain-pause-mode") :pin "2356c8c") ;; commit date 2020/07/27
#+END_SRC
#+BEGIN_SRC emacs-lisp
;;(explain-pause-mode t)
#+END_SRC
** Spell-fu
*** Config
#+begin_src emacs-lisp
(after! org-mode
  (add-hook 'org-mode-hook
            (lambda ()
              (setq spell-fu-faces-exclude '(org-meta-line org-link org-code))
              (spell-fu-mode))))
#+end_src
** Lorem Ipsum Generator
*** Package
#+begin_src emacs-lisp :tangle packages.el
(package! lorem-ipsum :recipe (:host github :repo "jschaf/emacs-lorem-ipsum")
  :pin "da75c15") ;; Aug 19, 2019
#+end_src
*** Config
#+begin_src emacs-lisp
(use-package! lorem-ipsum)
#+end_src
* Additional Macros
Here are some additional functions/macros that could help you configure Doom:
- ~load!~ for loading external *.el files relative to this one
- ~use-package~ for configuring packages
- ~after!~ for running code after a package has loaded
- ~add-load-path!~ for adding directories to the `load-path', relative to this file. Emacs searches the ~load-path~ when you load packages with ~require~ or ~use-package~.
- ~map!~ for binding new keys

To get information about any of these functions/macros, move the cursor over the highlighted symbol at press 'K' (non-evil users must press 'C-c g k'). This will open documentation for it, including demos of how they are used.

You can also try 'gd' (or 'C-c g d') to jump to their definition and see how they are implemented.
* My Functions/Macros
** Some snippets for detecting system
*** Detect System
#+begin_src emacs-list :tangle no
system-type
#+end_src
Will return these among others:
~gnu/linux~
~windows-nt~
~darwin~
~FreeBSD~
*** Detect WSL under Windows
#+begin_src emacs-lisp :tangle no
(string-match "-[Mm]icrosoft" operating-system-release)
#+end_src
Will return nil if not present, or an integer representing the string index.
~operating-system-release~ will return the Microsoft kernel under WSL, but will
return nil under system type windows-nt.
** Terminal program ends
This will kill the buffer and return back to the last buffer visited, when you stop running a program in a terminal.
#+BEGIN_SRC emacs-lisp
;;(defadvice term-handle-exit
;;    (after term-kill-buffer-on-exit activate)
;;  (kill-buffer)
;;  (switch-to-buffer (car (car (window-prev-buffers)))))
#+END_SRC
** Programs I run
These are some convenience functions for programs I run often.
#+BEGIN_SRC emacs-lisp
(defun system-distribution()
  (if (and (string= system-type "gnu/linux")
           (executable-find "lsb_release"))
      (replace-regexp-in-string ;; NixOS echos extraneous quotes in lsb_release
       "\\W" ""
       (car (split-string (shell-command-to-string "lsb_release -sd"))))
    system-type))
(setq! system-distro (system-distribution))

(use-package! multi-term
  :config
  ;; These have functions only work, once we have loaded multi-term
  (defun trh/run-term-program (program)
    "Make a multi-term buffer running program."
    (let ((multi-term-program program))
      (multi-term)))

  (defun aptitude ()
    "Run Aptitude"
    (interactive)
    (trh/run-term-program "aptitude"))

  (defun htop ()
    "Run Htop"
    (interactive)
    (trh/run-term-program "htop"))

  (defun neofetch ()
    (interactive)
    (ansi-term "neofetch")))
#+END_SRC
** Disable line numbers function
#+BEGIN_SRC emacs-lisp
(defun disable-line-numbers ()
  (display-line-numbers-mode -1))
#+END_SRC
** Functions for xdg desktop environment
#+begin_src emacs-lisp
(defun my/xdg-data-dirs ()
  "Returns a list of xdg-data-dirs. There's a similar function in counsel."
  (split-string (getenv "XDG_DATA_DIRS") ":"))

(defun my/find-soundfile (file)
  "Returns the path for a sound file if it is in xdg-data-dirs"
  (let ((xdg-path (car (seq-filter (lambda (x)
                                     (file-exists-p (concat x "/sounds/" file)))
                                   (my/xdg-data-dirs)))))
    (when xdg-path
      (concat xdg-path "/sounds/" file))))
#+end_src
** Neofetch
My attempt at writing a neofetch interface for Emacs
#+begin_src emacs-lisp
(defun my/get-image ()
  "/usr/src/stand/images/freebsd-logo-rev.png")

(defun my-neofetch ()
  (interactive)
  (if (executable-find "neofetch")
      (let ((sys-data (shell-command-to-string "neofetch --stdout")))
        (switch-to-buffer (get-buffer-create "*my-neofetch*"))
        (erase-buffer)
        (insert-image (create-image (my/get-image)))
        (insert sys-data))
    (message "ERROR: Need neofetch on your path for this to work.")))
#+end_src
* Run program
This is for running arbitrary programs I don't run often.
#+BEGIN_SRC emacs-lisp
(defun run-program (input)
  (interactive
   (list (read-shell-command "run command: ")))
  (let ((cmd (split-string input)))
    (dired-start-process (car cmd) (cdr cmd))))

(map! "C-!" #'run-program)
#+END_SRC
* COMMENT Emacs Frame Manager
The purpose of this module is managing Emacs windows in an environment without using EXWM. This will offer functions an emacsclient can run conditioned on the current state of the window, and fast terminal access within Emacs. This will work with X11, not sure what the implications are for Cocoa or Windows.
** Frame Names
First, we set up unique names for the X Window names, so we can easily reference these windows in an X Window environment. The names have random numbers, to make them easier to isolate among many windows in an X environment.
   #+BEGIN_SRC emacs-lisp
(defvar efm/frame-name "emacs-frame-manager998")
(defvar efm/shell-name "emacs-frame-manager336")
(defvar efm/org-name "emacs-frame-manager920")
   #+END_SRC
** Default buffer
The default buffer to load.
#+BEGIN_SRC emacs-lisp
(setq efm/default-buffer "*doom*")
#+END_SRC
** Extra frames
When emacs runs in daemon mode under systemd, emacsclient can, and sometimes will, create extra frames when you execute a command with emacsclient that does not need a frame, before any frames have been opened, and then execute emacsclient with a new frame. We keep track of legitimate frames, so we can just delete the unneeded frames. If you add new frames above that you intend to use, be sure to add them to this list, so they do not get inadvertently deleted.
   #+BEGIN_SRC emacs-lisp
(defvar efm/legit-frames (list efm/frame-name efm/shell-name efm/org-name "F1"))
   #+END_SRC
- Now the utility functions
  #+BEGIN_SRC emacs-lisp
(defun efm/list-illegite-frames ()
  "Lists visible illegitimate frames. Essentially all frames not in the efm/legit-frames list and is visible."
  (cl-remove-if
   (lambda (x)
     (seq-find (lambda (y)
                 (string= y
                          (frame-parameter x 'name))) efm/legit-frames))
   (cl-remove-if-not 'frame-visible-p (frame-list))))

(defun efm/kill-illegite-frames ()
  "Deletes the extra visible frames."
  (dolist (buf (efm/list-illegite-frames))
    (delete-frame buf)))
  #+END_SRC
** Frame management
Utility functions for frame management. These find frames, suspend frames, raise frames and maximize frames.
#+BEGIN_SRC emacs-lisp

(defun efm/find-frame (frame-name)
  "Returns a list of frames with frame-name."
  (cl-remove-if-not
   (lambda (x)
     (string= (frame-parameter x 'name) frame-name))
   (frame-list)))

(defun efm/maximized-p (frame)
  "Returns true if frame is maximized or fullboth."
  (cdr (assoc 'fullscreen (frame-parameters frame))))

(defun efm/create-frame (frame-name frame-title)
  "Creates a maximized frame, raised and in focus."
  (make-frame-on-display (getenv "DISPLAY") `((name . ,frame-name)
                                              (title . ,frame-title)
                                              (fullscreen . maximized)
                                              (window-system . x)))
  (let ((frame (car (efm/find-frame frame-name))))
    (frame-focus frame)
    (x-focus-frame frame)))

(defun efm/raise-frame (frame)
  "Raises a frame and puts it in focus."
  (raise-frame frame)
  (select-frame frame)
  (x-focus-frame frame))

(defun efm/frame-focus-maximize (frame &optional command)
  "Raise, focus, and maximize a frame."
  (efm/raise-frame frame)
  (modify-frame-parameters frame '((fullscreen . maximized)))
  (when command
    (eval (list (intern command)))))

(defun efm/run-command (command)
  (cond ((string-equal command default-buffer) (switch-to-buffer efm/default-buffer))
        ((string-equal command "doom-buffer") (+doom-dashboard/open (car (efm/find-frame efm/frame-name))))))

(defun efm/start-client-with-command (name title &optional command skip-taskbar)
  "Create a new frame, executing command."
  (efm/create-frame name title)
  (if command
      (eval (list (intern command)))
    (efm/run-command "doom-buffer"))
  (when skip-taskbar
    (modify-frame-parameters (car (efm/find-frame name))
                             '((skip-taskbar t)
                               (undecorated t)))))

(defun efm/raise-or-start (name title &optional command toggle skip-taskbar)
  "If frame with name does not exist, create it, otherwise raise, focus and maximize the existing frame."
  (let ((frame (car (efm/find-frame name))))
    (if frame
        (if (and (frame-focus-state frame)
                 (efm/maximized-p frame)
                 (or (and (null command) (null toggle))
                     (and (not (null command)) (not (null toggle)))))
            (progn (select-frame frame)
                   (suspend-frame))
          (efm/frame-focus-maximize frame command))
      (efm/start-client-with-command name title command skip-taskbar))))

#+END_SRC
* Applications
** Email
Use Gmail in gnus
*** Settings
#+BEGIN_SRC emacs-lisp
(setq!
 send-mail-function 'smtpmail-send-it
 message-send-mail-function 'smtpmail-send-it
 user-mail-address "trhawes@gmail.com"
 smtpmail-starttls-credentials '(("smtp.gmail.com" "587" nil nil))
 smtpmail-auth-credentials (expand-file-name "~/.authinfo.gpg")
 smtpmail-default-smtp-server "smtp.gmail.com"
 smtpmail-smtp-server "smtp.gmail.com"
 smtpmail-smtp-service 587
 smtpmail-debug-info t
 starttls-extra-arguments nil
 starttls-gnutls-program "/usr/bin/gnutls-cli"
 starttls-extra-arguments nil
 starttls-use-gnutls t
 )
#+END_SRC
** Web browser
*** Settings
#+BEGIN_SRC emacs-lisp

(setq! browse-url-generic-program
       (or (executable-find "brave-browser")
           (executable-find "microsoft-edge-stable")
           (executable-find "chromium")
           (executable-find "firefox")))

(setq! browse-url-default-browser 'eww-browse-url)
;;(setq shr-external-browser 'browse-url-generic)
(setq!
 browse-url-handlers
 '(
   ("youtube\\.com" . browse-url-generic)
   ("vimeo\\.com" . browse-url-generic)
   ("facebook\\.com" . browse-url-firefox)
   ("reddit\\.com" . browse-url-firefox)
   ("." . browse-url-generic)))
#+END_SRC
** Epub reader
*** Packages
#+begin_src emacs-lisp :tangle packages.el
(package! nov :recipe (:host "https://depp.brause.cc/" :repo "nov.el.git"))
#+end_src
*** Config
#+begin_src emacs-lisp
(defun my/nov-font-setup ()
  (face-remap-add-relative 'variable-pitch :family "Liberation Serif"
                                           :height 1.0))
(use-package! nov
  :mode ("\\.epub\\'" . nov-mode))
(add-hook! 'nov-mode-hook 'my/nov-font-setup)
#+end_src
** Search Tools
*** Google
**** Package
#+BEGIN_SRC emacs-lisp :tangle packages.el
(package! google-this)
#+END_SRC
**** Config
Default mapping is "C-c / t"
#+BEGIN_SRC emacs-lisp
(google-this-mode 1)
#+END_SRC
** UUID
Allows you to generate a UUID in a writable buffer, with ~M-x uuidgen~.
*** Package
#+BEGIN_SRC emacs-lisp :tangle packages.el
(package! uuidgen :recipe
  (:host github :repo "kanru/uuidgen-el")
  :pin "b50e6fe") ;; Commit date 2020/08/16
#+END_SRC
** Magit
*** Settings
**** git path
Because nix is now installing git from my package choices, I need to make sure my system git is preferred. I will need to change for nonstandard git installs.
#+begin_src emacs-lisp
(let ((git-path (split-string (executable-find "git") "/")))
  (when (member ".nix-profile" git-path)
    (cond
     ((file-executable-p "/usr/bin/git") (setq! magit-git-executable "/usr/bin/git"))
     ((file-executable-p "/user/local/bin/git") (setq! magit-git-executable "/usr/local/bin/git"))
     ((file-executable-p "/usr/pkg/bin/git") (setq! magit-git-executable "/usr/pkg/bin/git"))
     (t "default"))))
#+end_src
** Emacs Application framework
*** Package
There is no package file for eaf, so dependencies have to be manually managed. Download Emacs Application Framework [[https://github.com/manateelazycat/emacs-application-framework.git][here]].
- ~epc~: is managed below in the programming section.
- ~deferred~: is included in Doom Emacs
#+begin_src emacs-lisp :tangle packages.el
(package! ctable :recipe
  (:host github :repo "kiwanami/emacs-ctable")
  :pin "48b7374") ;; Commit date 2021/1/28

(package! s :recipe
  (:host github :repo "magnars/s.el")
  :pin "08661ef") ;; Commit date 2021/6/16
#+end_src
*** Config
#+begin_src emacs-lisp
(when (file-directory-p "~/.local/share/emacs/emacs-application-framework")
  (use-package! eaf
    :load-path "~/.local/share/emacs/emacs-application-framework"
    :custom
    (eaf-browser-continue-where-left-off t)
    :config
    (eaf-setq eaf-browser-enable-adblocker "true")
    (eaf-bind-key scroll_up "C-n" eaf-pdf-viewer-keybinding)
    (eaf-bind-key scroll_down "C-p" eaf-pdf-viewer-keybinding)
    (eaf-bind-key take_photo "p" eaf-camera-keybinding)
    (eaf-bind-key nil "M-q" eaf-browser-keybinding))) ;; unbind, see more in the Wiki)
#+end_src
* Pcomplete
** pcmpl-args
*** package
#+begin_src emacs-lisp :tangle packages.el
(package! pcmpl-args :recipe (:host github :repo "JonWaltman/pcmpl-args.el")
  :pin "43229e1") ;; Commit date May 10, 2022
#+end_src
*** config
#+begin_src emacs-lisp
(after! eshell-mode
  (use-package! pcmpl-args))
#+end_src
** apt
#+BEGIN_SRC emacs-lisp
(defconst pcmpl-apt-commands
  '("autoclean" "clean" "full-upgrade" "policy" "show"
    "autopurge" "depends" "help" "purge" "showsrc"
    "autoremove" "dist-upgrade" "install" "rdepends" "source"
    "build-dep" "download" "list" "remove" "update"
    "changelog" "edit-sources" "moo" "search" "upgrade"))
(defun pcomplete/apt ()
  (pcomplete-here* pcmpl-apt-commands))
#+END_SRC
** apt-get
#+BEGIN_SRC emacs-lisp
(defconst pcmpl-apt-get-commands
  '("autoclean" "check" "dselect-upgrade" "remove"
    "autoremove" "clean" "indextargets" "source" "moo"
    "build-dep" "dist-upgrade" "install" "update"
    "changelog" "download" "purge" "upgrade"))
(defun pcomplete/apt-get ()
  (pcomplete-here* pcmpl-apt-get-commands))
#+END_SRC
** exercism
#+BEGIN_SRC emacs-lisp
(defconst pcmpl-exercism-commands
  '("configure" "help" "submit" "upgrade" "workspace" "prepare"
    "download" "open" "troubleshoot" "version")
  "List of `exercism' commands")
(defun pcomplete/exercism ()
  (pcomplete-here* pcmpl-exercism-commands))
#+END_SRC
** COMMENT git
#+BEGIN_SRC emacs-lisp
(defconst pcmpl-git-commands
  '("add" "bisect" "branch" "checkout" "clone"
    "commit" "diff" "fetch" "grep"
    "init" "log" "merge" "mv" "pull" "push" "rebase"
    "reset" "rm" "show" "status" "tag" )
  "List of `git' commands")

(defvar pcmpl-git-ref-list-cmd "git for-each-ref refs/ --format='%(refname)'"
  "The `git' command to run to get a list of refs")

(defun pcmpl-git-get-refs (type)
  "Return a list of `git' refs filtered by TYPE"
  (with-temp-buffer
    (insert (shell-command-to-string pcmpl-git-ref-list-cmd))
    (goto-char (point-min))
    (let ((ref-list))
      (while (re-search-forward (concat "^refs/" type "/\\(.+\\)$") nil t)
        (add-to-list 'ref-list (match-string 1)))
      ref-list)))

(defun pcomplete/git ()
  "Completion for `git'"
  ;; Completion for the command argument.
  (pcomplete-here* pcmpl-git-commands)
  ;; complete files/dirs forever if the command is `add' or `rm'
  (cond
   ((pcomplete-match (regexp-opt '("add" "rm")) 1)
    (while (pcomplete-here (pcomplete-entries))))
   ;; provide branch completion for the command `checkout'.
   ((pcomplete-match "checkout" 1)
    (pcomplete-here* (pcmpl-git-get-refs "heads")))))
#+END_SRC
* Dired
** Packages
*** s3ed S3 for Dired
#+begin_src emacs-lisp :tangle packages.el
(package! s3ed :recipe (:host github :repo "mattusifer/s3ed")
  :pin "2234444") ; Commit date Sep 29, 2020
#+end_src
** Settings
#+BEGIN_SRC emacs-lisp
(setq! dired-hide-details-mode t)
(setq! ranger-override-dired-mode t)
(use-package! s3ed)
#+END_SRC
** Functions
#+BEGIN_SRC emacs-lisp
;; Dired code taken from https://oremacs.com/2015/01/04/dired-nohup/
;; This incorporates nohup with starting a process
(after! dired
  (use-package! dired-aux)

  (defvar dired-filelist-cmd
    '(("vlc" "-L")))

  (defun dired-start-process (cmd &optional file-list)
    (interactive
     (let ((files (dired-get-marked-files
                   t current-prefix-arg)))
       (list
        (dired-read-shell-command "& on %s: "
                                  current-prefix-arg files)
        files)))
    (let (list-switch)
      (start-process
       cmd nil shell-file-name
       shell-command-switch
       (format
        "nohup 1>/dev/null 2>/dev/null %s \"%s\""
        (if (and (> (length file-list) 1)
                 (setq list-switch
                       (cadr (assoc cmd dired-filelist-cmd))))
            (format "%s %s" cmd list-switch)
          cmd)
        (mapconcat #'expand-file-name file-list "\" \""))))))
#+END_SRC
* Shells
** Eshell
*** Packages
**** Completion
Because I would much rather define my own completions using elisp and pcomplete.
#+begin_src emacs-lisp :tangle packages.el
(package! fish-completion :disable t)
#+end_src
**** Emulate a Terminal
***** Package
#+begin_src emacs-lisp :tangle packages.el
(package! emacs-eat :recipe (:type git :repo "https://codeberg.org/akib/emacs-eat.git" :branch "master")
  :pin "d85744b48a") ;; Commit date May 15, 2023
#+end_src
***** Config
#+begin_src emacs-lisp
(use-package eat
  :config
  (add-hook! 'eshell-load-hook #'eat-eshell-mode)
  ;;(add-hook! 'eshell-load-hook #'eat-eshell-visual-command-mode)
  )
#+end_src
**** [[https://github.com/tom-tan/esh-help][esh-help]] for Eshell help
Shows help in minibuffer when typing an elisp command in eshell.
***** Package
#+BEGIN_SRC emacs-lisp :tangle packages.el
(package! esh-help :recipe
  (:host github :repo "tom-tan/esh-help") :pin "417673e") ;;Commit date 2019/9/4
#+END_SRC
***** Config
#+begin_src emacs-lisp
(after! eshell
  (setup-esh-help-eldoc))
(map! :map eshell-mode-map
      :desc "Elisp Command Help" :g "C-h h" #'esh-help-run-help)
#+end_src
**** [[https://github.com/porterjamesj/virtualenvwrapper.el][Virtualenvwrapper]] for Emacs
[[https://virtualenvwrapper.readthedocs.io/en/latest/][Virtualenvwrapper]] is a set of extensions for more easily managing multiple virtualenv's for Python. It is available on Debian and Ubuntu systems. This is an Emacs module that interfaces with that system, making it easy to use in Eshell and Emacs proper.
#+BEGIN_SRC emacs-lisp :tangle packages.el
(package! virtualenvwrapper :recipe
  (:host github :repo "porterjamesj/virtualenvwrapper.el")
  :pin "c7e8450") ;; Commit date 2021/4/7
#+END_SRC
#+BEGIN_SRC emacs-lisp
(after! virtualenvwrapper
  (setq! venv-location "~/.virtualenvs/"))
#+END_SRC
*** Settings
**** Directory path for eshell-directory-name
#+BEGIN_SRC emacs-lisp
(after! eshell-z
  (setq! eshell-directory-name (concat doom-private-dir "eshell"))
  (setq! eshell-aliases-file (concat doom-private-dir "eshell/alias")))
#+END_SRC
**** Custom magit commands in eshell
#+BEGIN_SRC emacs-lisp
(after! eshell
  (defun eshell/mgit (&rest args)
    "Using magit in eshell"
    (eshell-eval-using-options
     "mgit" args
     '((?s "status" nil status "Show git status for repo.")
       (?l "log" nil log "Show git log for all branches")
       (nil "help" nil nil "Show this usage information")
       :show-usage)
     (eshell-do-eval
      (eshell-parse-command
       (cond
        (status "magit-status")
        (log "magit-log-all-branches")))
      t))))
#+END_SRC
**** Custom dpkg commands in eshell
#+BEGIN_SRC emacs-lisp
(after! eshell
  (defun eshell/deb (&rest args)
    "deb command for eshell"
    (eshell-eval-using-options
     "deb" args
     '((?f "find" t find "list available packages matching a pattern")
       (?i "installed" t installed "list installed debs matching a pattern")
       (?l "list-files" t list-files "list files of a package")
       (?s "show" t show "show an available package")
       (?v "version" t version "show the version of an installed package")
       (?w "where" t where "find the package containing the given file")
       (nil "help" nil nil "show this usage information")
       :show-usage)
     (eshell-do-eval
      (eshell-parse-command
       (cond
        (find
         (format "apt-cache search %s" find))
        (installed
         (format "dlocate -l %s | grep '^.i'" installed))
        (list-files
         (format "dlocate -L %s | sort" list-files))
        (show
         (format "apt-cache show %s" show))
        (version
         (format "dlocate -s %s | egrep '^(Package|Status|Version):'" version))
        (where
         (format "dlocate %s" where))))
      t))))
#+END_SRC
**** Eshell history settings
#+BEGIN_SRC emacs-lisp
(after! eshell
  (setq eshell-history-size 1024)

                                        ; So the history vars are defined
  (load "em-hist")

  ;; Don't ask, just save
  ;;(message "eshell-ask-to-save-history is %s" eshell-ask-to-save-history)
  (if (boundp 'eshell-save-history-on-exit)
      (setq eshell-save-history-on-exit t))

  ;; For older(?) version
  ;;(message "eshell-ask-to-save-history is %s" eshell-ask-to-save-history)
  (when (boundp 'eshell-ask-to-save-history)
    (setq eshell-ask-to-save-history 'always)))
#+END_SRC
**** COMMENT Custom prompt
No longer desired with aweshell now enabled.
***** Packages
#+BEGIN_SRC emacs-lisp :tangle no
(package! eshell-prompt-extras :recipe
  (:host github :repo "zwild/eshell-prompt-extras")
  :pin "d7d874c") ;;Commit date 2020/11/14
#+END_SRC
***** Config
#+BEGIN_SRC emacs-lisp :tangle no
(after! eshell
  (use-package! eshell-prompt-extras
    :config
    ;; for virtualenvwrapper stuff
    (with-eval-after-load "esh-opt"
      (require 'virtualenvwrapper)
      (venv-initialize-eshell)
      (autoload 'epe-theme-lambda "eshell-prompt-extras")
      (setq eshell-highlight-prompt nil
            eshell-prompt-function 'epe-theme-lambda
            eshell-prompt-regexp "^[^#\nλ]*[#λ] "
            epe-show-python-info t
            epe-path-style 'single))))
#+END_SRC
*** Modules
#+BEGIN_SRC emacs-lisp
(after! eshell
  (add-to-list 'eshell-modules-list 'eshell-tramp 'esh-opt))
#+END_SRC
*** Preferred functions and variables
#+BEGIN_SRC emacs-lisp
(after! eshell
  (setq eshell-prefer-lisp-functions t))
#+END_SRC
*** Password caching
#+BEGIN_SRC emacs-lisp
(after! eshell
  (setq password-cache t) ; enable password caching
  (setq password-cache-expiry 300)) ; for 5 minutes (time in secs)
#+END_SRC
*** Progress bar for apt in minibuffer
#+BEGIN_SRC emacs-lisp
;; Progress bars, like apt in the status/echo area
(after! eshell
  (advice-add
   'ansi-color-apply-on-region
   :before 'ora-ansi-color-apply-on-region)

  (defun ora-ansi-color-apply-on-region (begin end)
    "Fix progress bars for e.g. apt(8).
     Display progress in the mode line instead."
    (let ((end-marker (copy-marker end))
          mb)
      (save-excursion
        (goto-char (copy-marker begin))
        (while (re-search-forward "\0337" end-marker t)
          (setq mb (match-beginning 0))
          (when (re-search-forward "\0338" end-marker t)
            (ora-apt-progress-message
             (substring-no-properties
              (delete-and-extract-region mb (point))
              2 -2)))))))

  (defun ora-apt-progress-message (progress)
    (message
     (replace-regexp-in-string
      "%" "%%"
      (ansi-color-apply progress)))))
#+END_SRC
*** Visual commands
#+BEGIN_SRC emacs-lisp
;; Visual commands
;; defaults are ("vi" "screen" "top" "less" "more" "lynx" "ncftp" "pine" "tin" "trn" "elm")
(after! eshell
  (setq eshell-visual-commands '("vi" "screen" "top" "less" "more" "lynx" "ncftp" "pine" "tin" "trn" "elm"))
  (dolist (cmd '("tmux" "aptitude" "aws-shell" "neofetch" "htop" "radeontop"))
    (add-to-list 'eshell-visual-commands cmd)))
#+END_SRC
** Aweshell
*** Package
#+begin_src emacs-lisp :tangle packages.el
(package! aweshell :recipe (:host github :repo "manateelazycat/aweshell")
  :pin "31004dd") ;;Commit date 2020/6/23
#+end_src
*** Config
#+begin_src emacs-lisp
(use-package! aweshell)
#+end_src
** Shell-pop
Default Doom eshell (disabled, but left for reference).
#+BEGIN_SRC emacs-lisp
(map! "<f3>" 'aweshell-toggle)
#+END_SRC
Aweshell toggle.
#+begin_src emacs-lisp
;;(map! "<f3>" 'aweshell-dedicated-toggle)
#+end_src
* Deft
#+BEGIN_SRC emacs-lisp
(setq! deft-extensions '("org" "md" "txt" "tex"))
(setq! deft-directory "~/org-files/deft")
(setq! deft-recursive t)
(map! "<f8>" 'deft)
#+END_SRC
* ChatGPT
** Package
#+begin_src emacs-lisp :tangle packages.el
(package! chatgpt
  :recipe (:host github :repo "joshcho/ChatGPT.el" :files ("dist" "*.el"))
  :pin "b31337e") ;; Commit date Sept 10, 2023
#+end_src
** Config
#+begin_src emacs-lisp
(use-package! chatgpt
  :defer t
  :bind ("C-c q" . chatgpt-query))

#+end_src
* Emacs Jupyter
** Package
#+begin_src emacs-lisp :tangle packages.el
(package! jupyter :recipe
  (:host github :repo "emacs-jupyter/jupyter")
  :pin "f97f4b5") ;; Commit date 2024/7/16
#+end_src
** Config
#+begin_src emacs-lisp
(use-package! jupyter)
#+end_src
* Org-mode
** Basic Config
*** Variables
**** For all
#+begin_src emacs-lisp
(setq! org-startup-folded t
       org-hide-emphasis-markers t)
#+end_src
**** Separate org-work from org-home
#+begin_src emacs-lisp
(if (string= system-name "scholasticus")
    (setq! org-directory "~/org-files/GTD/work"
           org-agenda-files (file-expand-wildcards "~/org/GTD/work/*.org"))
  (setq org-directory "~/org-files/GTD/home"
        org-agenda-files (file-expand-wildcards "~/org/GTD/home/*.org")))
#+end_src
*** Hooks
#+BEGIN_SRC emacs-lisp
(add-hook! 'org-mode-hook
           #'disable-line-numbers
           #'org-indent-mode
           #'mixed-pitch-mode)
#+END_SRC
*** Keymap for org-mode
#+BEGIN_SRC emacs-lisp
(after! org
  (map! :map org-mode-map
        :g (kbd "<C-down-mouse-1>") #'org-open-at-point))
#+END_SRC
** Jira
#+BEGIN_SRC emacs-lisp :tangle packages.el
(package! org-jira :recipe
  (:host github :repo "ahungry/org-jira")
  :pin "63a74d4") ;; Commit date 2023/4/13
#+END_SRC
#+BEGIN_SRC emacs-lisp
(after! org
  (use-package! org-jira
    :init
    (setq! jiralib-url "https://inindca.atlassian.net"
           org-jira-working-dir (concat
                                  (if (boundp 'doom-private-dir)
                                      doom-private-dir
                                    user-emacs-directory) "jira")))
  (when (not (file-directory-p org-jira-working-dir))
    (make-directory org-jira-working-dir)))
#+END_SRC
** Org modules
*** Convert to BBCode
**** Package
#+begin_src emacs-lisp :tangle packages.el
(package! ox-bb :recipe
  (:host github
   :repo "timotheosh/ox-bb"
   :branch "world-anvil-bbcode"))
#+end_src
**** Config
#+begin_src emacs-lisp
(after! org
  (use-package! ox-bb))
#+end_src
*** Confluence
#+begin_src emacs-lisp
(use-package! ox-confluence)
#+end_src
*** Github Flavored Markdown
#+BEGIN_SRC emacs-lisp :tangle packages.el
(package! ox-gfm)
#+END_SRC
#+BEGIN_SRC emacs-lisp
(after! org
  (use-package! ox-gfm))
#+END_SRC
*** Pretty bullets
#+BEGIN_SRC emacs-lisp :tangle packages.el
(package! org-bullets)
#+END_SRC
#+BEGIN_SRC emacs-lisp
(after! org
  (use-package! org-bullets
  :config
  (add-hook! 'org-mode-hook #'org-bullets-mode)))
#+END_SRC
*** Convert org to OpenOffice
**** Config
#+BEGIN_SRC emacs-lisp
(use-package! ox-odt)
#+END_SRC
*** Convert to revealjs
**** package
#+BEGIN_SRC emacs-lisp :tangle packages.el
(package! org-reveal :recipe (:host github :repo "yjwen/org-reveal"))
#+END_SRC
**** config
#+BEGIN_SRC emacs-lisp
(add-hook! org-mode-hook #'ox-reveal
  (use-package! ox-reveal))
#+END_SRC
*** Inline Racket
**** Package
#+BEGIN_SRC emacs-lisp :tangle packages.el
(package! ob-racket :recipe
  (:host github :repo "hasu/emacs-ob-racket")
  :pin "da3526c") ;; Commit date 2021/3/4
#+END_SRC
**** Config
#+BEGIN_SRC emacs-lisp
(after! org
  (use-package! ob-racket)
  ;;(add-to-list 'org-babel-load-languages '(racket . t))
  )

#+END_SRC
*** Javascript
#+begin_src emacs-lisp
(use-package! ob-js)
;;(add-to-list 'org-babel-load-languages '(js . t))
(defun ob-js-insert-session-header-arg (session)
  "Insert ob-js `SESSION' header argument.
- `js-comint'
- `skewer-mode'
- `Indium'
"
  (interactive (list (completing-read "ob-js session: "
                                      '("js-comint" "skewer-mode" "indium"))))
  (org-babel-insert-header-arg
   "session"
   (pcase session
     ("js-comint" "\"*Javascript REPL*\"")
     ("skewer-mode" "\"*skewer-repl*\"")
     ("indium" "\"*JS REPL*\""))))

(define-key org-babel-map (kbd "J") 'ob-js-insert-session-header-arg)
#+end_src
*** Python
#+begin_src emacs-lisp
(after! org
  (use-package ob-python)
  ;;(add-to-list 'org-babel-load-languages '(python . t))
  )
#+end_src
*** Lisp
#+begin_src emacs-lisp
(after! org
  (use-package! ob-lisp)
  ;;(add-to-list 'org-babel-load-languages '(lisp . t))
  )
#+end_src
*** Clojure
#+begin_src emacs-lisp
(after! org
  (use-package! ob-clojure)
  ;;(add-to-list 'org-babel-load-languages '(clojure . t))
  )
#+end_src
*** Ansible
**** Package
#+begin_src emacs-lisp :tangle packages.el
(package! ob-ansible :recipe
  (:host github :repo "timotheosh/ob-ansible")
  :pin "a95914c") ;; Commit date 2017/8/18
#+end_src
**** Config
#+begin_src emacs-lisp
(after! org
  (use-package! ob-ansible)
  ;;(add-to-list 'org-babel-load-languages '(ansible . t))
  )
#+end_src
*** Projectile
#+BEGIN_SRC emacs-lisp :tangle packages.el
(package! org-projectile :recipe
  (:host github :repo "IvanMalison/org-projectile")
  :pin "96a57a4")
#+END_SRC
#+BEGIN_SRC emacs-lisp
(after! org
  (use-package! org-projectile
    :bind (("C-c n p" . org-projectile-project-todo-completing-read)
           ("C-c c" . org-capture))
    :config
    (if (string= system-name "scholasticus")
        (setq! org-projectile-projects-file
               "~/org/GTD/work/code-projects.org")
      (setq! org-projectile-projects-file
             "~/org/GTD/home/code-projects.org"))
    (setq! org-agenda-files (append org-agenda-files (org-projectile-todo-files)))
    (push (org-projectile-project-todo-entry) org-capture-templates)))
#+END_SRC
*** org2blog
#+BEGIN_SRC emacs-lisp :tangle packages.el
(package! org2blog :recipe
  (:host github :repo "org2blog/org2blog")
  :pin "c1b386f") ;; Commit date 2021/4/21
#+END_SRC
#+BEGIN_SRC emacs-lisp
(after! org
  (use-package! org2blog
    :config
    (setq! org2blog/wp-blog-alist
           '(("timhawes"
              :url "https://timhawes.wordpress.com/xmlrpc.php"
              :username "timotheosh")
             ("desktopstability"
              :url "https://desktopstability.wordpress.com/xmlrpc.php"
              :username "timotheosh")))))
#+END_SRC
*** org-protocol
#+BEGIN_SRC emacs-lisp
;;(use-package! org-protocol)
#+END_SRC
*** obtt
obtt is an acronym for "org-babel-tangle templates".
#+BEGIN_SRC emacs-lisp :tangle packages.el
(package! obtt :recipe
  (:host github :repo "timotheosh/obtt")
  :pin "0285efb") ;; Commit date 2020/6/23
#+END_SRC
#+BEGIN_SRC emacs-lisp
(setq! obtt-templates-dir (concat
                              (if (boundp 'doom-private-dir)
                                  doom-private-dir
                                user-emacs-directory) "obtt")
       obtt-seed-name ".obtt")
(after! org
  (use-package! obtt))
(when (not (file-directory-p obtt-templates-dir))
    (make-directory obtt-templates-dir))
#+END_SRC
*** org-sidebar
**** package
#+begin_src emacs-lisp :tangle packages.el
(package! org-sidebar :recipe (:host github :repo "alphapapa/org-sidebar")
  :pin "288703b") ;; Commit date Sep 12, 2021
#+end_src
** COMMENT Publishing
#+begin_src emacs-lisp
(setq! org-publish-project-alist
       '(("naurrnen-website"
          :recursive t
          :base-directory "~/org-files/Projects/naurrnen-website/src/"
          :publishing-directory "~/org-files/Projects/naurrnen-website/public/"
          :author "Tim Hawes © 2023"
          :with-author t           ;; Don't include author name
          :with-creator t            ;; Include Emacs and Org versions in footer
          :with-toc nil              ;; Include a table of contents
          :with-title nil
          :section-numbers nil       ;; Don't include section numbers
          :time-stamp-file nil       ;; Don't include time stamp in file
          :exclude "setup.org\\|navbar.org"
          :auto-sitemap t
          :sitemap-filename "sitemap.org"
          :base-extension "org"
          :publishing-function org-html-publish-to-html)
         ("naurrnen-artifacts"
          :recursive t
          :base-directory "~/org-files/Projects/naurrnen-website/src/"
          :publishing-directory "~/org-files/Projects/naurrnen-website/public/"
          :base-extension "js\\|css\\|png\\|jpg"
          :publishing-function org-publish-attachment)))
(setq! org-html-validation-link nil
        org-html-head-include-scripts nil
        org-html-head-include-default-style nil
        org-html-head nil)
;;        org-html-head "<link rel=\"stylesheet\" href=\"https://cdn.simplecss.org/simple.min.css\" />")
#+end_src
** gimel
*** package
#+begin_src emacs-lisp :tangle packages.el
;;(package! gimel :recipe (:host github :repo "timotheosh/gimel"
;;                         :files ("resources/emacs/gimel.el")))
#+end_src
*** config
#+begin_src emacs-lisp
(add-to-list 'load-path "/home/thawes/src/projects/gimel/resources/emacs/")
(require 'gimel)
(add-hook 'after-save-hook #'gimel-run-on-save)
#+end_src
** Jupyter support
#+begin_src emacs-lisp
(use-package! ob-jupyter)
(use-package! org)
#+end_src
** language support
This is run after all languages have been added above.

#+begin_src emacs-lisp
(org-babel-do-load-languages 'org-babel-load-languages
                             '((emacs-lisp . t)
                               (ansible . t)
                               (clojure . t)
                               (lisp . t)
                               (python . t)
                               (js . t)
                               (racket . t)
                               (jupyter . t)))
#+end_src
* adoc-mode
** Package
#+begin_src emacs-lisp :tangle packages.el
(package! adoc-mode :recipe (:host github :repo "bbatsov/adoc-mode")
  :pin "05914c7") ;; Commit date Sept 5, 2023

(package! org-asciidoc :recipe (:host github :repo "yashi/org-asciidoc")
  :pin "c0b8db5") ;; Commit date Oct 16, 2023
#+end_src
** COMMENT Config
#+begin_src emacs-lisp
(use-package! adoc-mode
  :mode (("\\.adoc\\'"  . adoc-mode)
         ("\\.asciidoc\\'" . adoc-mode)))

(after! org (use-package! ox-asciidoc))
#+end_src
* Book Readers
** Calibre
*** Package
#+begin_src emacs-lisp :tangle packages.el
(package! calibredb :recipe
  (:host github :repo "chenyanming/calibredb.el")
  :pin "cb93563") ;; Commit date 2021/6/4
#+end_src
*** Config
#+begin_src emacs-lisp
(use-package! calibredb
  :config
  (setq calibredb-root-dir "~/Documents/Sync/CalibreBooks"
        calibredb-db-dir (expand-file-name "metadata.db" calibredb-root-dir)))
#+end_src
** Epub Reader
*** Package
#+begin_src emacs-lisp :tangle packages.el
(package! nov :recipe (:host nil :repo "https://depp.brause.cc/nov.el.git") :pin "b3c7cc28e9") ;; Commit date 2021/3/23
(package! visual-fill-column :recipe (:host github :repo "joostkremers/visual-fill-column") :pin "6fa9e79") ;;Commit date 2021/4/19
#+end_src
*** Config
#+begin_src emacs-lisp
(defun my-nov-font-setup ()
  (face-remap-add-relative 'variable-pitch :family "Liberation Serif"
                                           :height 1.0))
(add-hook 'nov-mode-hook 'my-nov-font-setup)

(setq nov-text-width t)
(setq visual-fill-column-center-text t)
(add-hook 'nov-mode-hook 'visual-line-mode)
(add-hook 'nov-mode-hook 'visual-fill-column-mode)
(add-to-list 'auto-mode-alist '("\\.epub\\'" . nov-mode))
#+end_src
* RSS Reader
Settings for Elfeed rss feed reader
#+BEGIN_SRC emacs-lisp
(setq! elfeed-feeds
       '(("http://www.garynorth.com/mysite.xml" economics)
         ("http://feeds.fee.org/FEE-Freeman" economics)
         ("https://www.eff.org/rss" technology politics)
         ("https://emacsredux.com/feed.xml" blog emacs)
         ("http://emacsrocks.com/atom.xml" blog emacs)
         ("http://pragmaticemacs.com/feed/" blog emacs)
         ("https://stackoverflow.com/feeds/tag?tagnames=emacs&sort=newest" stackoverflow emacs)
         ("https://www.reddit.com/r/emacs.rss" reddit technology emacs)
         ("https://planet.emacslife.com/atom.xml" technology emacs)
         ("https://www.reddit.com/r/lisp.rss" reddit technology lisp)
         ("https://www.reddit.com/r/clojure.rss" reddit technology lisp clojure)
         ("https://www.reddit.com/r/Racket.rss" reddit technology lisp racket)
         ("https://stevelosh.com/rss.xml" blog technology lisp)
         ("http://planet.lisp.org/rss20.xml" blog technology lisp)
         ("https://lispblog.xach.com/rss" blog technology lisp)
         ("https://lispnews.wordpress.com/rss.xml" blog technology lisp)
         ("https://borretti.me/feed.xml" blog technology)
         ("https://stackoverflow.com/feeds/tag?tagnames=common-lisp&sort=newest" stackoverflow lisp)
         ("https://planet.kde.org/global/atom.xml/" blog desktop kde)
         ("https://www.kdevelop.org/rss.xml" blog desktop kde kdevelop)))

#+END_SRC
* Httpd Server
We use simple-httpd for emacs, since that comes with impatient-mode.
** Package
#+begin_src emacs-lisp :tangle packages.el
(package! simple-httpd :recipe
  (:host github :repo "skeeto/emacs-web-server")
  :pin "3982c55") ;; Commit date 2023/12/29
#+end_src
* ZeroMQ
Needed for ~emacs-jupiter~
** Package
#+begin_src emacs-lisp :tangle packages.el
(package! zmq :recipe
  (:host github :repo "nnicandro/emacs-zmq")
  :pin "1d9d5a3") ;; Commit date 2024/7/16
#+end_src
* Programming Languages
** General
*** Settings
**** Safe variables for Projectile configurations
Predefining ahead of time. Each language can ~add-to-list~ to get their specific commands added.
#+begin_src emacs-lisp
(setq safe-local-variable-values '())
(setq enable-local-variables :all)
#+end_src
**** [[https://github.com/Malabarba/aggressive-indent-mode][Aggressive indent]] for better formatting of code.
Package should be explicitly added on a per programming language basis. It is especially effective with lisp languages.
***** Package
Just ~(add-hook! /programming-mode-hook/ #'aggressive-indent-mode)~ to activate.
#+BEGIN_SRC emacs-lisp :tangle packages.el
(package! aggressive-indent :recipe
  (:host github :repo "Malabarba/aggressive-indent-mode")
  :pin "b0ec004") ;; Commit date 2020/8/24
#+END_SRC
**** Company settings
#+begin_src emacs-lisp
(after! company
  (setq! company-idle-delay 0.5))
#+end_src
**** [[https://github.com/company-mode/company-quickhelp][Company-quickhelp]] for on the fly documentation.
#+BEGIN_SRC emacs-lisp :tangle packages.el
(package! company-quickhelp :recipe
  (:host github :repo "company-mode/company-quickhelp")
  :pin "9505fb0") ;; Commit date 2022/12/12
#+END_SRC
#+BEGIN_SRC emacs-lisp
(after! company
  (add-hook! 'company-mode-hook #'company-quickhelp-mode)
  (setq! company-quickhelp-delay nil))
(map! :map company-active-map
      :g "C-c h" #'company-quickhelp-manual-begin)
#+END_SRC
**** Code folding
Origami is a minor mode that enables code folding. Learn more [[https://github.com/gregsexton/origami.el][here]]. ~lsp-origami~ uses ~lsp~ to inform Origami. Learn more [[https://github.com/emacs-lsp/lsp-origami][here]].
#+BEGIN_SRC emacs-lisp :tangle packages.el
(package! origami :recipe
  (:host github :repo "gregsexton/origami.el")
  :pin "e558710") ;; Commit date 2020/3/31
(package! lsp-origami :recipe
  (:host github :repo "emacs-lsp/lsp-origami")
  :pin "bedea3d") ;; Commit date 2021/1/26
#+END_SRC
#+BEGIN_SRC emacs-lisp
(after! prog-mode
  (map! :map origami-mode-map
        (:g "C-<tab>" #'origami-recursively-toggle-node
         :g "C-<iso-lefttab>" #'origami-toggle-all-nodes))
  (add-hook! 'prog-mode-hook #'origami-mode)
  (add-hook! 'lsp-after-open-hook #'lsp-origami-try-enable))
#+END_SRC
**** Smartparens for paredit functionality is many different programming language modes
***** Config
#+BEGIN_SRC emacs-lisp
(after! prog-mode
  (sp-with-modes sp--lisp-modes
    ;; disable ', it's the quote character!
    (sp-local-pair "'" nil :actions nil)
    ;; also only use the pseudo-quote inside strings where it serve as
    ;; hyperlink.
    (sp-local-pair "`" "'" :when '(sp-in-string-p sp-in-comment-p))
    (sp-local-pair "`" nil
                   :skip-match
                   (lambda (ms mb me)
                     (cond
                      ((equal ms "'")
                       (or (sp--org-skip-markup ms mb me)
                           (not (sp-point-in-string-or-comment))))
                      (t (not (sp-point-in-string-or-comment))))))))
(after! org
  (sp-with-modes 'org-mode
    (sp-local-pair "\\[" "\\]")
    (sp-local-pair "$" "$")
    (sp-local-pair "'" "'" :actions '(rem))
    (sp-local-pair "=" "=" :actions '(rem))
    (sp-local-pair "\\left(" "\\right)" :trigger "\\l(" :post-handlers '(sp-latex-insert-spaces-inside-pair))
    (sp-local-pair "\\left[" "\\right]" :trigger "\\l[" :post-handlers '(sp-latex-insert-spaces-inside-pair))
    (sp-local-pair "\\left\\{" "\\right\\}" :trigger "\\l{" :post-handlers '(sp-latex-insert-spaces-inside-pair))
    (sp-local-pair "\\left|" "\\right|" :trigger "\\l|" :post-handlers '(sp-latex-insert-spaces-inside-pair))))
#+END_SRC
***** Key Bindings
#+begin_src emacs-lisp
(map! :map smartparens-mode-map
      (:g "C-M-a" #'sp-beginning-of-sexp
       :g "C-M-e" #'sp-end-of-sexp

       ;;:g "C-<down>" #'sp-down-sexp) ;; Conflicts with REPL bindings
       ;;:g "C-<up>"   #'sp-up-sexp)   ;; Conflicts with REPL bindings
       :g "M-<down>" #'sp-backward-down-sexp
       :g "M-<up>"   #'sp-backward-up-sexp

       :g "C-M-f" #'sp-forward-sexp
       :g "C-M-b" #'sp-backward-sexp

       :g "C-M-n" #'sp-next-sexp
       :g "C-M-p" #'sp-previous-sexp

       :g "C-S-f" #'sp-forward-symbol
       :g "C-S-b" #'sp-backward-symbol

       :g "C-<right>" #'sp-forward-slurp-sexp
       :g "M-<right>" #'sp-forward-barf-sexp
       :g "C-<left>"  #'sp-backward-slurp-sexp
       :g "M-<left>"  #'sp-backward-barf-sexp

       :g "C-M-t" #'sp-transpose-sexp
       :g "C-M-k" #'sp-kill-sexp
       :g "C-k"   #'sp-kill-hybrid-sexp
       :g "M-k"   #'sp-backward-kill-sexp
       :g "C-M-w" #'sp-copy-sexp

       :g "C-M-d" #'delete-sexp

       :g "M-<backspace>" #'backward-kill-word
       :g "C-<backspace>" #'sp-backward-kill-word
       :g [remap sp-backward-kill-word] #'backward-kill-word

       :g "M-[" #'sp-backward-unwrap-sexp
       :g "M-]" #'sp-unwrap-sexp

       :g "C-x C-t" #'sp-transpose-hybrid-sexp))
#+end_src
**** Match parenthesis/brackets
#+BEGIN_SRC emacs-lisp
(after! prog-mode
  (defun my/match-paren (arg)
    "Go to the matching paren if on a paren; otherwise insert normally."
    (interactive "p")
    (cond ((looking-at "\\s\(") (forward-list 1) (backward-char 1))
          ((looking-at "\\s\)") (forward-char 1) (backward-list 1))
          (t (self-insert-command (or arg 1)))))
  (map! :map prog-mode-map
        :g "<backtab>" 'my/match-paren))
#+END_SRC
**** Lisp extra fontlock
***** Package
#+BEGIN_SRC emacs-lisp :tangle packages.el
(package! lisp-extra-font-lock :recipe
  (:host github :repo "Lindydancer/lisp-extra-font-lock")
  :pin "4605ecc") ;; Commit date 2018/10/8
#+END_SRC
** Emacs-epc
For talking with other languages. The main docs start [[https://github.com/kiwanami/emacs-epc][here]].
*** Package
#+begin_src emacs-lisp :tangle packages.el
(package! epc :recipe
  (:host github :repo "kiwanami/emacs-epc")
  :pin "e1bfa5c")
#+end_src
** Exercism.io
Personal project for projectile to understand exercism.io projects. The project is in [[https://github.com/timotheosh/exercism-mode][github]].
*** Package
#+begin_src emacs-lisp :tangle packages.el
;;(package! exercism-mode :recipe (:host github :repo "timotheosh/exercism-mode"))
#+end_src
*** Config
#+begin_src emacs-lisp
(when (file-directory-p (expand-file-name "~/src/projects/exercism-mode"))
  (use-package! exercism-mode
    :after projectile
    :load-path "~/src/projects/exercism-mode"
    :config (exercism-mode +1))
  (map! :map exercism-mode-map
        :leader
        (:prefix ("x" . "Exercism")
         :desc "Submit current file"       "s" #'exercism-submit-file
         :desc "Download exercise"         "d" #'exercism-download-exercise
         :desc "Paste download command"    "p" #'exercism-download-command
         :desc "Refresh current exercise"  "r" #'exercism-refresh-exercise
         :desc "Open exercise description" "w" #'exercism-open-exercise-web))
  (map! :map ranger-mode-map
        :leader
        (:prefix ("x" . "exercism")
         :desc "Submit marked files"      "x" #'exercism-dired-submit-marked-files)))
#+end_src
** Clojure
*** defaults
#+BEGIN_SRC emacs-lisp
(add-hook! 'clojure-mode-hook
           #'lsp-deferred
           #'smartparens-strict-mode
           #'aggressive-indent-mode
           #'lisp-extra-font-lock-mode)
(add-hook! 'clojurescript-mode-hook
           #'lsp-deferred
           #'smartparens-strict-mode
           #'aggressive-indent-mode
           #'lisp-extra-font-lock-mode)
(add-hook! 'clojurec-mode-hook
           #'lsp-deferred
           #'smartparens-strict-mode
           #'aggressive-indent-mode
           #'lisp-extra-font-lock-mode)

(setq! gc-cons-threshold (* 100 1024 1024)
       read-process-output-max (* 1024 1024)
       treemacs-space-between-root-nodes nil
       company-minimum-prefix-length 1
       ;; lsp-enable-indentation nil ; uncomment to use cider indentation instead of lsp
       ;; lsp-enable-completion-at-point nil ; uncomment to use cider completion instead of lsp
       )

(use-package! cider
  :after clojure-mode
  :config
  (set-lookup-handlers! 'cider-mode nil))

(use-package! clj-refactor
  :after clojure-mode
  :config
  (set-lookup-handlers! 'clj-refactor-mode nil))
#+END_SRC
** Common Lisp
*** Settings
**** Config
#+begin_src emacs-lisp
(add-hook! 'lisp-mode-hook
           #'smartparens-strict-mode
           #'aggressive-indent-mode
           #'lisp-extra-font-lock-mode
           #'company-quickhelp-mode)

(map! :map sly-mrepl-mode-map
      (:g "<C-up>" #'comint-previous-input
       :g "<C-down>" #'comint-next-input))

#+end_src
**** Config Lisp Implementations
***** Find available Lisp implementations
The last implementation searched for will be the first (default) choice in sly. The roswell implementations should be treated separately in this case as their priorities are based on the ~*lisp-impl*~ variable below. Evaluate roswell last if you want their implementations listed first.
#+name: available-lisps
#+begin_src emacs-lisp :tangle no
(defvar *implementations* '())
;; This will all be nil if roswell is not installed.
(defvar ros-path (executable-find "ros")
  "Path ro ros program.")
(when ros-path

  (defun ros-filter (text)
    "Filter for finding all the lisp implementations ros manages."
    (string= (substring text 0 9) "Installed"))

  (defun is-sbcl? (impl)
    "Returns true if impl is sbcl-based"
    (and (> (length impl) 3)
         (string= (substring impl 0 4) "sbcl")))

  (defun is-ecl? (impl)
    "Returns true if impl is sbcl-based"
    (and (> (length impl) 2)
         (string= (substring impl 0 3) "ecl")))

  (defun ros-config (impl)
    (let ((retval (list  ros-path "-L" impl "-Q" "run")))
      (if (or (is-sbcl? impl)
              (is-ecl? impl))
          (list (intern (concat "roswell-" impl)) retval :coding-system 'utf-8-unix)
        (list (intern (concat "roswell-" impl)) retval))))

  (defvar *lisp-impl*
    '("sbcl"
      "sbcl-bin"
      "ecl"
      "abcl-bin")
    "Preferred lisp implementations to setup within Emacs by order of
priority. The first value will be the default implementation.")

  (defvar *setup-lisp*
    (let ((output (shell-command-to-string "ros list installed")))
      (let ((result (mapcar (lambda (text) (car (split-string text "/" t)))
                            (cl-remove-if #'ros-filter (split-string output "\n" t)))))
        (dolist (impl (reverse *lisp-impl*) result)
          (when (cl-position impl result :test #'string=)
            (setq result (cons impl (remove impl result))))))))
  (setq *implementations* (mapcar #'ros-config *setup-lisp*)))

;; Look for sbcl
(defvar sbcl-path (executable-find "sbcl"))

(when sbcl-path
  (push (list 'sbcl (list sbcl-path) :coding-system 'utf-8-unix) *implementations*))

,*implementations*
#+end_src
#+BEGIN_SRC emacs-lisp :noweb yes
(after! sly
  (setq! sly-lisp-implementations '<<available-lisps()>>))
#+END_SRC
**** Hyperspec lookup
Open CL REPL and execute: ~(ql:quickload "clhs")~, then follow instructions.
~C-c C-d h~ on common lisp directive, and it should open the definition in the default web browser.
#+BEGIN_SRC emacs-lisp
(after! lisp-mode
  (when (file-exists-p "/home/thawes/.roswell/lisp/quicklisp/clhs-use-local.el")
    (load! "/home/thawes/.roswell/lisp/quicklisp/clhs-use-local.el")))
(map! :after sly
      :map lisp-mode-map
      :g "C-c C-d h" #'sly-documentation-lookup)
#+END_SRC
**** Common Lisp Language Server
This is functional, but untested on Doom Emacs, and disabled for now. Most of the functionality for this is given with Sly/Slime.

In order to use, be sure to install the language server first, by running ~ros install cxxxr/cl-lsp~
See also the Github repo [[https://github.com/cxxxr/cl-lsp.git][cl-lsp]].
#+BEGIN_SRC emacs-lisp
;; (add-to-list 'lsp-language-id-configuration '(lisp-mode "lisp"))
;;   (lsp-register-client
;;    (make-lsp-client :new-connection (lsp-stdio-connection "cl-lsp")
;;                     :major-modes '(lisp-mode)
;;                     :server-id 'cl-lsp))
;;   (add-hook 'lisp-mode-hook 'lsp-deferred)
#+END_SRC
** Csh and tcsh mode
*** package
#+begin_src emacs-lisp :tangle packages.el
(package! csh-mode :recipe (:host github :repo "tcsh-org/tcsh"
                            :files ("csh-mode.el")) :pin "d075ab5") ;; Commit date: 2023-06-27
#+end_src
*** config
#+begin_src emacs-lisp
;; Enable csh-mode
(use-package! csh-mode
  :mode ("\\.csh\\'" "\\.cshrc\\'" "\\.tcshrc\\'"))
#+end_src
** Emacs Lisp
*** Settings
#+BEGIN_SRC emacs-lisp
(after! company
  (add-to-list 'company-backends 'company-elisp))
(add-hook! 'emacs-lisp-mode-hook
           #'eldoc-mode
           #'smartparens-strict-mode
           #'aggressive-indent-mode
           #'lisp-extra-font-lock-mode
           #'company-quickhelp-mode)
#+END_SRC
*** Safe-variables
#+begin_src emacs-lisp
(mapc (lambda (cmd) (add-to-list 'safe-local-variable-values cmd))
      '((projectile-project-test-cmd . #'stringp)))
#+end_src
** Fennel
Fennel, a Lisp that compiles to Lua
*** Package
#+begin_src emacs-lisp :tangle packages.el
(package! fennel-mode :recipe
  (:host gitlab :repo "technomancy/fennel-mode")
  :pin "59ab0234") ;; Commit date 2021/4/9
#+end_src
*** Config
TODO: FIXME: There is a conflict between fennel bound keys and Sly.
#+begin_src emacs-lisp
(add-to-list 'auto-mode-alist '("\\.fnl\\'" . fennel-mode))
(add-hook! 'fennel-mode
           #'aggressive-indent-mode
           #'smartparens-global-strict-mode)
#+end_src
** GDScript
** Gerbil Scheme
This is a work in progress, and currently inop.
*** Package
Both Gambit and Gerbil modes are needed. Be sure to install the treadmill server package in order to use treadmill. From the shell, run:
~gxpkg install github.com/thunknyc/gerbil-treadmill~
#+BEGIN_SRC emacs-lisp :tangle no
(package! gambit :recipe
  (:host github
   :repo "gambit/gambit"
   :files ("misc/gambit.el"))
  :pin "baf7de6") ;; This is version 4.9.3

(package! gerbil-mode :recipe
  (:host github
   :repo "vyzo/gerbil"
   :files ("etc/gerbil-mode.el"))
  :pin "4189bec") ;; This is version 0.16

(package! treadmill :recipe
  (:host github
   :repo "thunknyc/emacs-treadmill")
  :pin "271d117") ;; Commit date 2019/1/7
#+END_SRC
*** Config
#+BEGIN_SRC emacs-lisp :tangle no
(use-package! gerbil-mode
  :when (getenv "GERBIL_HOME")
  :mode (("\\.ss\\'"  . gerbil-mode)
         ("\\.pkg\\'" . gerbil-mode))
  :init
  (map! :map comint-mode-map
        (:g "<C-up>" #'comint-previous-input
         :g "<C-down>" #'comint-next-input))
  (setf gerbil-home (getenv "GERBIL_HOME"))
  :config
  (use-package! gambit
    :config
    (setf gambit-home (getenv "GAMBIT_HOME"))
    (add-hook! 'inferior-scheme-mode-hook #'gambit-inferior-mode))
  (setq! gerbil-program-name (concat gerbil-home "/bin/gxi"))
  (let ((tags (locate-dominating-file default-directory "TAGS")))
    (when tags (visit-tags-table tags)))
  (visit-tags-table (concat gerbil-home "/src/TAGS")))

#+END_SRC
** Groovy
Just for Jenkinsfile support
*** package
#+BEGIN_SRC emacs-lisp :tangle packages.el
(package! groovy-mode :recipe
  (:host github :repo "Groovy-Emacs-Modes/groovy-emacs-modes")
  :pin "7b8520b") ;; Commit date 2023/3/18
#+END_SRC
*** config
#+begin_src emacs-lisp
(use-package! groovy-mode
  :config
  (setq groovy-indent-offset 2))
#+end_src

** HTML
*** Impatience mode for realtime editing of html
**** Package
#+BEGIN_SRC emacs-lisp :tangle packages.el
(package! web-mode :recipe
  (:host github :repo "fxbois/web-mode")
  :pin "8ef4793") ;; Commit date 2021/1/31

(package! impatient-mode :recipe
  (:host github :repo "skeeto/impatient-mode")
  :pin "cbddfd5") ;; Commit date 2020/7/23
#+END_SRC
**** Hooks
#+BEGIN_SRC emacs-lisp
(use-package! web-mode
  :mode (("\\.html"        . web-mode)
         ("\\.htm"         . web-mode)
         ("\\.mustache\\'" . web-mode)
         ("\\.phtml\\'"    . web-mode)
         ("\\.as[cp]x\\'"  . web-mode))
  :config
  (setq! web-mode-markup-indent-offset 2)
  (setq! web-mode-css-indent-offset 2)
  (setq! web-mode-code-indent-offset 2)
  (setq! web-mode-comment-style 2)
  ;;(setq! web-mode-enable-auto-indentation nil)
  (setq! web-mode-enable-css-colorization t)
  (setq! web-mode-enable-block-face t)
  (setq! web-mode-enable-comment-keywords t)
  (setq! web-mode-enable-heredoc-fontification t)

  (setq! web-mode-enable-auto-quoting t)
  (setq! web-mode-enable-auto-pairing t)
  (setq! web-mode-tag-auto-close-style 2))

(add-hook! 'web-mode-hook #'impatient-mode)
(add-hook! 'css-mode-hook #'impatient-mode)
#+END_SRC
** Java
*** Springboot Initializer
#+begin_src emacs-lisp
(defun springboot-quickstart ()
  (interactive)
  (use-package! lsp-java)
  (lsp-java-spring-initializr))
#+end_src
** Javascript
*** Default hooks
#+begin_src emacs-lisp
(add-hook! 'js2-mode-hook
           #'aggressive-indent-mode
           #'smartparens-strict-mode
           #'lsp)
#+end_src
*** Packages for org-mode
This is needed for org-mode babel.
**** package
#+begin_src emacs-lisp :tangle packages.el
(package! js-comint :recipe
  (:host github :repo "redguardtoo/js-comint")
  :pin "7920252") ;; Commit Date Dec 19, 2021
#+end_src
*** Websocket
Needed by Indium
**** Package
#+BEGIN_SRC emacs-lisp :tangle packages.el
(package! websocket :recipe
  (:host github :repo "ahyatt/emacs-websocket")
  :pin "40c208e") ;; Commit date 2023/8/8  Old: :pin "34e1112"
#+END_SRC
*** Indium
**** Package
#+BEGIN_SRC emacs-lisp :tangle packages.el
(package! indium :recipe
  (:host github :repo "NicolasPetton/Indium")
  :pin "8499e15") ;; Commit date 2021/5/9
#+END_SRC
*** Node-REPL
**** Package
#+begin_src emacs-lisp :tangle packages.el
(package! nodejs-repl :recipe
  (:host github :repo "abicky/nodejs-repl.el")
  :pin "3b84105") ;; Commit date 2020/8/2
#+end_src
**** Config
#+begin_src emacs-lisp
(map! :map js2-mode-map
      :prefix "C-x"
      :g "C-e" #'nodejs-repl-send-last-expression)
(map! :map js2-mode-map
      :prefix "C-c"
      :g "C-j" #'nodejs-repl-send-line
      :g "C-r" #'nodejs-repl-send-region
      :g "C-c" #'nodejs-repl-send-buffer
      :g "C-k" #'nodejs-repl-load-file
      :g "C-z" #'nodejs-repl-switch-to-repl)
#+end_src
*** Safe-variables
#+begin_src emacs-lisp
(mapc (lambda (cmd) (add-to-list 'safe-local-variable-values cmd))
      '((projectile-project-configure-cmd . "npm install")
        (projectile-project-test-cmd . "npm run test")
        (projectile-project-test-cmd . "npm test")))
#+end_src
*** npm.el (npm-mode)
**** Package
#+begin_src emacs-lisp :tangle packages.el
(package! npm :recipe
  (:host github :repo "shaneikennedy/npm.el")
  :pin "2bd5441") ;; Commit date Sep 30, 2021
#+end_src
**** Config
#+begin_src emacs-lisp
(add-hook! 'js2-mode-hook #'npm-mode)
#+end_src
*** projectile settings
#+begin_src emacs-lisp
(projectile-register-project-type 'npm '("package.json")
                                  :project-file "package.json"
                                  :compile "npm install"
                                  :test "npm test"
                                  :run "npm start"
                                  :test-suffix ".spec")
#+end_src
*** Snippets
**** React
***** Component
#+begin_src snippet :tangle snippets/rjsx-mode/rsc.yasnippet
# -*- mode: snippet -*-
# name: React#Component
# key: rsc
# --
import React from 'react';

export default function ${`(file-name-nondirectory (file-name-sans-extension buffer-file-name))`}() {
    return (
        <div>
          $0
        </div>
    )
}
#+end_src
** Jenkinsfile
*** package
#+BEGIN_SRC emacs-lisp :tangle packages.el
(package! jenkinsfile-mode :recipe
  (:host github :repo "john2x/jenkinsfile-mode")
  :pin "65bf392") ;; Commit date 2020/9/29
#+END_SRC
*** config
#+BEGIN_SRC emacs-lisp
(add-to-list 'auto-mode-alist '("/Jenkinsfile" . jenkinsfile-mode))
(add-to-list 'auto-mode-alist '("/jenkinsfile" . jenkinsfile-mode))
(add-hook! 'jenkinsfile-mode (lambda () (setq! groovy-indent-offset 2)))
#+END_SRC
** Lua
*** Love2d Minor-mode
**** Package
#+begin_src emacs-lisp :tangle packages.el
(package! love-minor-mode :recipe
  (:host github :repo "ejmr/love-minor-mode")
  :pin "3ca8f34") ;; Commit date 2017/7/27
#+end_src
**** Config
#+begin_src emacs-lisp
(add-hook! 'lua-mode-hook #'love-minor-mode)
#+end_src
** Markdown
*** Impatient mode for realtime editing of markdown
#+BEGIN_SRC emacs-lisp
(defun markdown-html-filter (buffer)
  (princ (with-current-buffer buffer
           (format "<!DOCTYPE html><html><title>Impatient Markdown</title><xmp theme=\"united\" style=\"display:none;\"> %s  </xmp><script src=\"http://strapdownjs.com/v/0.2/strapdown.js\"></script></html>" (buffer-substring-no-properties (point-min) (point-max))))
         (current-buffer)))
(add-hook! 'markdown-mode-hook #'impatient-mode
  (lambda () (imp-set-user-filter #'markdown-html-filter)))
#+END_SRC

** Python
*** Packages
**** pyright
***** package
#+begin_src emacs-lisp :tangle packages.el
(package! lsp-pyright :recipe (:host github :repo "emacs-lsp/lsp-pyright")
  :pin "54a2acd") ;; Commit date Feb 25, 2023
#+end_src
*** Config
#+begin_src emacs-lisp
(defun projectile-pyenv-mode-set ()
  "Set pyenv version matching project name."
  (when (= major-mode 'python-mode)
    (let ((project (projectile-project-name)))
      (if (member project (pyenv-mode-versions))
          (pyenv-mode-set project)
        (pyenv-mode-unset)))))

;;(add-hook! 'projectile-after-switch-project-hook #'projectile-pyenv-mode-set)
(add-hook! 'python-mode-hook
           #'anaconda-mode
           #'anaconda-eldoc-mode
           (lambda ()  (use-package! lsp-pyright))
           #'lsp-deferred)

(after! python
  (setq! python-indent-offset 4)
  (use-package! pyenv-mode)
  (when (executable-find (expand-file-name "~/.pyenv/shims/ipython"))
    (setq! python-shell-interpreter (expand-file-name "~/.pyenv/shims/ipython")
           python-shell-interpreter-interactive-arg "-i"
           python-shell-interpreter-args "-i --no-banner --simple-prompt --pprint"
           python-shell-prompt-regexp "In \[[0-9]+\]: "
           python-shell-prompt-output-regexp "Out\\[[0-9]+\\]: "
           python-shell-completion-native-enable nil)
    (setenv "PYTHONUNBUFFERED" "1")))
#+end_src
** Racket
*** Package
#+begin_src emacs-lisp :tangle packages.el
(package! racket-mode :recipe
  (:host github :repo "greghendershott/racket-mode")
  :pin "abd59fd") ;; Commit date 2021/5/17
#+end_src
*** Config
#+begin_src emacs-lisp
(add-hook! 'racket-mode-hook
           #'smartparens-strict-mode
           #'aggressive-indent-mode
           #'lisp-extra-font-lock-mode
           #'company-mode)
#+end_src
** Yaml
#+begin_src emacs-lisp
(add-hook! yaml-mode-hook
  (lambda ()
    (prettify-symbols-mode -1)))
#+end_src
* Scripts
** FreeBSD Server Script
#+begin_src shell :shebang "#!/bin/sh" :tangle scripts/emacsd
# PROVIDE: emacsd
# REQUIRE: login # after login

# Emacs daemon
#
# Define emacsd_user and emacd_socket in your /etc/rc.conf file
. /etc/rc.subr

name="emacsd"
rcvar=emacsd_enable

start_cmd="${name}_start"
stop_cmd="${name}_stop"
load_rc_config $name
: ${emacsd_enable:=no}
: ${_msg="Emacs daemon started."}
: ${emacsd_user:=nobody}
: ${emacsd_socket:=server}
: ${emacsd_args:=""}

emacsd_start()
{
    su ${emacsd_user} -c "env HOME=/home/${emacsd_user} /usr/local/bin/emacs ${emacsd_args} --daemon=${emacsd_socket}"
}
emacsd_stop()
{
    su ${emacsd_user} -c "/usr/local/bin/emacsclient --socket=${emacsd_socket} --eval \"(kill-emacs)\""
}
run_rc_command "$1"
#+end_src
* Pending Packages
These are packages I find cool, and might use in the future. I place them here so I can easily find them in the future.
** Aweshell
*** Package
From the make of multi-term, this is eshell on steroids with multi-eshell capability
#+begin_src emacs-lisp :tangle no
(package! aweshell :recipe (:host github :repo "manateelazycat/aweshell")
  :pin "31004dd") ;;Commit date 2020/6/23
#+end_src
*** Config
Details found [[https://github.com/manateelazycat/aweshell][here]].
** Selectrum
A smart replacement for ivy, helm, and ido. You'll need to disable ivy in your init.el before using this. You'll probably have to remap many keys as well. More details found [[https://github.com/raxod502/selectrum][here]].
*UPDATE*: Tried using package. Really was not impressed enough by it to use over ivy. I don't think an overhauled completion library excites me much. Plus still missing icons for display.
*** Package
#+begin_src emacs-lisp :tangle no
(package! selectrum :recipe
  (:host github :repo "raxod502/selectrum") :pin "909f614") ;;Commit date 2021/5/17
#+end_src
** Purpose
Once upon a time, I worked on some parts of a large project. I found myself using all kinds of buffers - python files, python interpreter, bash terminal, grep, dired, ibuffer. When I navigated the code, Emacs opened all sorts of buffers in all sorts of windows, and when I finally discovered what variable or function I needed, the window layout was messed up and I had to look for the original file I was working on.
What I was missing was a way to limit which buffers can be displayed in which windows. E2WM helped me somewhat, but wasn't flexible enough. Enter Purpose.

What Purpose does, is assign a purpose to each window and each buffer. This way, any window can display only a certain kind of buffers. Also, Purpose lets the user decide which windows can be used for any purpose, and which windows should stick to one purpose.
What this all should mean, if Purpose is successful, is less time spent fighting Emacs over the window layout and where to display buffers, a pleasant user experience and more time for fun or important work.

Purpose is not meant to be as extensive as E2WM. It has three main goals:

1. provide an easy and reliable way for the user to maintain a consistent window layout
2. provide a framework for extensions that make use of the window layout
3. hopefully, be a step towards IDE-like packages in the future (seriously)

More [[https://github.com/bmag/emacs-purpose/wiki][here]].

*UPDATE:* Actually looks like it has less features than ~perspective-mode~, which I have not fully explored yet.
#+begin_src emacs-lisp :tangle no
(package! purpose :recipe
  (:host github :repo "bmag/emacs-purpose")
  :pin "1a55629") ;; Commit date 2021/4/23
#+end_src
